# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Choosewindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_second_window(object):
    def setupUi(self, second_window):
        second_window.setObjectName("second_window")
        second_window.resize(520, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(second_window.sizePolicy().hasHeightForWidth())
        second_window.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget = QtWidgets.QWidget(second_window)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 220, 309, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.choose = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.choose.setContentsMargins(0, 0, 0, 0)
        self.choose.setObjectName("choose")
        self.rock = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rock.setObjectName("rock")
        self.choose.addWidget(self.rock)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.choose.addItem(spacerItem)
        self.scissor = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.scissor.setObjectName("scissor")
        self.choose.addWidget(self.scissor)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.choose.addItem(spacerItem1)
        self.paper = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.paper.setObjectName("paper")
        self.choose.addWidget(self.paper)
        self.round = QtWidgets.QLabel(second_window)
        self.round.setGeometry(QtCore.QRect(210, 10, 91, 31))
        self.round.setObjectName("round")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(second_window)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(120, 30, 261, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.character = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.character.setContentsMargins(0, 0, 0, 0)
        self.character.setObjectName("character")
        self.you = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.you.setObjectName("you")
        self.character.addWidget(self.you)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.character.addItem(spacerItem2)
        self.computer = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.computer.setObjectName("computer")
        self.character.addWidget(self.computer)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(second_window)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(120, 150, 261, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.scores = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.scores.setContentsMargins(0, 0, 0, 0)
        self.scores.setObjectName("scores")
        self.score1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.score1.setObjectName("score1")
        self.scores.addWidget(self.score1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.scores.addItem(spacerItem3)
        self.score2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.score2.setObjectName("score2")
        self.scores.addWidget(self.score2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(second_window)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(120, 100, 261, 78))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.two_choice = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.two_choice.setContentsMargins(0, 0, 0, 0)
        self.two_choice.setObjectName("two_choice")
        self.your_choice = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.your_choice.setObjectName("your_choice")
        self.two_choice.addWidget(self.your_choice)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.two_choice.addItem(spacerItem4)
        self.computer_choice = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.computer_choice.setObjectName("computer_choice")
        self.two_choice.addWidget(self.computer_choice, 0, QtCore.Qt.AlignHCenter)
        self.exit = QtWidgets.QPushButton(second_window)
        self.exit.setGeometry(QtCore.QRect(420, 20, 93, 291))
        self.exit.setObjectName("exit")

        self.retranslateUi(second_window)
        self.exit.clicked.connect(second_window.hide)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(second_window)

    def retranslateUi(self, second_window):
        _translate = QtCore.QCoreApplication.translate
        second_window.setWindowTitle(_translate("second_window", "choose"))
        self.rock.setText(_translate("second_window", "石头"))
        self.scissor.setText(_translate("second_window", "剪刀"))
        self.paper.setText(_translate("second_window", "布"))
        self.round.setText(_translate("second_window", "Round -n"))
        self.you.setText(_translate("second_window", "ning"))
        self.computer.setText(_translate("second_window", "电脑"))
        self.score1.setText(_translate("second_window", "得分1"))
        self.score2.setText(_translate("second_window", "得分2"))
        self.your_choice.setText(_translate("second_window", "选择1"))
        self.computer_choice.setText(_translate("second_window", "选择2"))
        self.exit.setText(_translate("second_window", "不想玩了"))
