# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(520, 320)
        mainwindow.setMinimumSize(QtCore.QSize(520, 320))
        mainwindow.setMaximumSize(QtCore.QSize(520, 320))
        self.background = QtWidgets.QLabel(mainwindow)
        self.background.setGeometry(QtCore.QRect(0, 0, 520, 320))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background.sizePolicy().hasHeightForWidth())
        self.background.setSizePolicy(sizePolicy)
        self.background.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background.setAutoFillBackground(False)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("../pictures/pic.png"))
        self.background.setObjectName("background")
        self.pushButton_2 = QtWidgets.QPushButton(mainwindow)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 190, 111, 101))
        self.pushButton_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_2.setAcceptDrops(False)
        self.pushButton_2.setAutoFillBackground(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(mainwindow)
        self.checkBox.setGeometry(QtCore.QRect(160, 260, 171, 19))
        self.checkBox.setAutoFillBackground(True)
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(mainwindow)
        self.label.setGeometry(QtCore.QRect(180, 20, 151, 61))
        self.label.setLineWidth(-1)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")

        self.retranslateUi(mainwindow)
        self.checkBox.toggled['bool'].connect(self.pushButton_2.setEnabled)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "???"))
        self.pushButton_2.setText(_translate("mainwindow", "点击开始:-)"))
        self.checkBox.setText(_translate("mainwindow", "提示：游戏共5个回合"))
        self.label.setText(_translate("mainwindow", "这个游戏很简单"))
